# Generated by Django 5.2.1 on 2025-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_analfabetismo',
            field=models.CharField(choices=[('funcional', 'Funcional'), ('absoluto', 'Absoluto')], max_length=20),
        ),
    ]
