# Generated by Django 5.2.1 on 2025-05-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        ('usuarios', '0002_alter_usuario_senha_alter_usuario_tipo_analfabetismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
